services:
      catrowebadmin.filesystem:
              class: Symfony\Component\Filesystem\Filesystem
              public: false

      catrowebadmin.command.init:
              class: Catrobat\AppBundle\Commands\InitDirectoriesCommand
              arguments: ["@catrowebadmin.filesystem","%catrobat.file.storage.dir%"]
              calls:
                - [setProgramfileDirectory, ["%catrobat.file.storage.dir%"]]
                - [setExtractDirectory, ["%catrobat.file.extract.dir%"]]
                - [setScreenshotDirectory, ["%catrobat.screenshot.dir%"]]
                - [setThumbnailDirectory, ["%catrobat.thumbnail.dir%"]]
              tags:
                -  { name: console.command }

      catrowebadmin.command.import:
              class: Catrobat\AppBundle\Commands\ProgramImportCommand
              arguments: ["@catrowebadmin.filesystem","@usermanager","@programmanager"]
              tags:
                -  { name: console.command }

      catrowebadmin.command.refresh:
              class: Catrobat\AppBundle\Commands\RefreshCommand
              arguments: ["@catrowebadmin.filesystem"]
              tags:
                -  { name: console.command }

      command.reset:
              class: Catrobat\AppBundle\Commands\ResetCommand
              tags:
                -  { name: console.command }

      command.purge:
              class: Catrobat\AppBundle\Commands\PurgeCommand
              tags:
                -  { name: console.command }

      command.backup.create:
              class: Catrobat\AppBundle\Commands\CreateBackupCommand
              tags:
                -  { name: console.command }

      command.backup.restore:
              class: Catrobat\AppBundle\Commands\RestoreBackupCommand
              tags:
                -  { name: console.command }


      catrowebadmin.command.import.legacy:
              class: Catrobat\AppBundle\Commands\ImportLegacyCommand
              arguments: ["@catrowebadmin.filesystem","@usermanager","@programmanager", "@doctrine.orm.entity_manager"]
              tags:
                -  { name: console.command }

      command.remix.count:
              class: Catrobat\AppBundle\Commands\CreateRemixCount
              arguments: ["@catrowebadmin.filesystem","@usermanager","@programmanager", "@doctrine.orm.entity_manager"]
              tags:
                -  { name: console.command }
                